'use client';
import {useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import type {Run} from '@/lib/models';
export default function Trend({runs}:{runs:Run[]}){
 const [range,setRange]=useState('30 runs');const [point,setPoint]=useState<number|null>(null);
 const history=[...runs.slice(0,range==='7 runs'?7:30)].reverse();const data=history.map(r=>r.score);const x=(i:number)=>48+i*(622/Math.max(1,data.length-1));const y=(v:number)=>195-v*1.6;const coords=data.map((v,i)=>`${x(i)},${y(v)}`);const average=data.length?Math.round(data.reduce((a,b)=>a+b,0)/data.length):0;const delta=data.length>1?data[data.length-1]-data[0]:0;
 return <section className="panel trend"><div className="panel-head"><div><h3>Quality over time</h3><p>Follow the quality of your recent uploads.</p></div><div className="segment">{['7 runs','30 runs'].map(r=><button key={r} aria-pressed={range===r} className={range===r?'selected':''} onClick={()=>setRange(r)}>{r}</button>)}</div></div><div className="chart-summary"><strong>{average}<small>/100</small></strong><span><ArrowUpRight size={14}/>{delta>0?'+':''}{delta} points <em>across displayed runs</em></span></div>{!data.length?<div className="empty"><p>Your quality history begins with your first upload.</p></div>:<svg className="trend-svg" viewBox="0 0 700 240" role="img" aria-label={`Quality scores across ${data.length} uploaded runs`}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8c79ed" stopOpacity=".23"/><stop offset="100%" stopColor="#8c79ed" stopOpacity="0"/></linearGradient></defs>{[0,25,50,75,100].map(v=><g key={v}><line x1="48" x2="674" y1={y(v)} y2={y(v)} stroke="#eeedf4" strokeDasharray="4 5"/><text x="12" y={y(v)+4} fill="#796f85" fontSize="10">{v}</text></g>)}<path d={`M ${coords[0]} L ${coords.join(' L ')} L ${x(data.length-1)},205 L 48,205 Z`} fill="url(#fill)"/><polyline points={coords.join(' ')} fill="none" stroke="#8270e8" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{data.map((v,i)=><g key={i} onMouseEnter={()=>setPoint(i)} onMouseLeave={()=>setPoint(null)}><circle cx={x(i)} cy={y(v)} r="12" fill="transparent" tabIndex={0} aria-label={`${history[i].project}: ${v} out of 100`} onFocus={()=>setPoint(i)} onBlur={()=>setPoint(null)}/><circle cx={x(i)} cy={y(v)} r={point===i||i===data.length-1?5:0} fill="#8270e8" stroke="white" strokeWidth="2"/>{point===i&&<text x={Math.min(645,Math.max(65,x(i)))} y={y(v)-15} fontSize="12" textAnchor="middle" fill="#5546db">{v}/100</text>}</g>)}{history.filter((_,i)=>i===0||i===history.length-1||i===Math.floor(history.length/2)).map(r=>{const i=history.indexOf(r);return <text key={r.id} x={Math.max(70,Math.min(645,x(i)))} y="233" textAnchor="middle" fill="#796f85" fontSize="10">{r.date.replace(', 2026','')}</text>})}</svg>}<div className="chart-legend"><i/>Overall score per run <span>{history.length} recent uploads</span></div></section>;
}
