import {z} from 'zod';
import {createHash} from 'node:crypto';
import {redactText,safeLocation} from './security';
const url=z.union([z.literal(''),z.url().refine(v=>/^https?:\/\//i.test(v)&&!new URL(v).username&&!new URL(v).password,'Use a public HTTP(S) URL without credentials')]);
export const projectInput=z.object({name:z.string().trim().min(1).max(100),description:z.string().max(500).default(''),websiteUrl:url.default(''),repository:url.default(''),framework:z.enum(['Auto Detect','Next.js','React','Angular','Vue','Vite','Other']).default('Auto Detect'),environment:z.enum(['Development','Staging','Production']).default('Development'),defaultBranch:z.string().min(1).max(100).default('main')}).strict();
export const gateInput=z.object({minimumScore:z.number().int().min(0).max(100),accessibility:z.number().int().min(0).max(100),seo:z.number().int().min(0).max(100),criticalIssues:z.number().int().min(0).max(10000),errors:z.number().int().min(0).max(10000)});
const issueInput=z.object({code:z.string().max(200).default('issue'),title:z.string().max(1000),message:z.string().max(5000).default(''),severity:z.enum(['info','warning','error','critical']).default('warning'),url:z.string().max(2000).optional(),file:z.string().max(1000).optional(),line:z.number().int().nonnegative().optional(),selector:z.string().max(1000).optional(),suggestion:z.object({shortFix:z.string().max(5000).optional()}).optional()});
export const uploadInput=z.object({projectId:z.uuid(),clientRunId:z.uuid(),cliVersion:z.string().max(50).default('unknown'),branch:z.string().max(100).optional(),commit:z.string().regex(/^[a-f0-9]{7,64}$/i).optional(),environment:z.enum(['Development','Staging','Production']).optional(),report:z.object({version:z.literal(2),framework:z.string().max(100),startedAt:z.iso.datetime(),finishedAt:z.iso.datetime(),duration:z.number().finite().min(0).max(86400000),overallScore:z.number().finite().min(0).max(100),routes:z.array(z.string().max(2000)).max(500).default([]),results:z.array(z.object({name:z.string().max(100),category:z.string().max(100).optional(),status:z.enum(['PASS','WARNING','FAIL','ERROR','SKIPPED']),score:z.number().finite().min(0).max(100).optional(),duration:z.number().finite().nonnegative(),message:z.string().max(10000).optional(),issues:z.array(issueInput).max(500).default([])})).max(100)}).refine(r=>new Date(r.finishedAt)>=new Date(r.startedAt),'Completion precedes start')}).strict();
export function sanitizeUpload(input:z.infer<typeof uploadInput>){return {...input,branch:redactText(input.branch??'main'),report:{...input.report,framework:redactText(input.report.framework),routes:input.report.routes.map(safeLocation),results:input.report.results.map(r=>({...r,message:redactText(r.message??''),issues:r.issues.map(i=>{const route=safeLocation(i.url??i.file??'');const selector=redactText(i.selector??'');const fingerprint=createHash('sha256').update(JSON.stringify([r.category??r.name,i.code,route,selector])).digest('hex');return {fingerprint,code:redactText(i.code),title:redactText(i.title),message:redactText(i.message),severity:i.severity,url:route,selector,suggestion:{shortFix:redactText(i.suggestion?.shortFix??'')}};})}))}}}
export type SanitizedUpload=ReturnType<typeof sanitizeUpload>;
