import {randomUUID,createHash} from 'node:crypto';
import {billingProvider} from '@/server/billing';
import {Prisma} from '@prisma/client';
import {z} from 'zod';
import {db} from '@/server/db';
import {endpoint,ApiError,readJson,sameOrigin} from '@/server/http';
import {requireWorkspace,allowRole} from '@/server/workspace';
import {projectInput,gateInput,uploadInput,sanitizeUpload} from '@/server/validation';
import {hashToken,newToken,verifySignature} from '@/server/security';
import {rateLimit,planFor} from '@/server/limits';
import {storeReport,removeReport,downloadReport} from '@/server/storage';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const handler=endpoint(async(req,requestId)=>{
 const path=new URL(req.url).pathname.replace('/api/v1/','').split('/');const [resource,id,action,child]=path;const method=req.method;
 if(resource==='health'&&method==='GET')return Response.json({status:'ok',service:'qa-check-cloud',version:'0.1.0'});
 if(resource==='billing'&&id==='webhooks'&&action==='razorpay'&&method==='POST'){
  if(!process.env.RAZORPAY_WEBHOOK_SECRET)throw new ApiError(503,'BILLING_NOT_CONFIGURED','Payment webhooks are not configured.');
  const text=await boundedText(req,256*1024);if(!verifySignature(text,req.headers.get('x-razorpay-signature')??'',process.env.RAZORPAY_WEBHOOK_SECRET))throw new ApiError(401,'INVALID_SIGNATURE','Webhook signature is invalid.');
  const event=z.object({event:z.string(),payload:z.object({subscription:z.object({entity:z.object({id:z.string()})}).optional()})}).parse(JSON.parse(text));const eventId=req.headers.get('x-razorpay-event-id');if(!eventId||eventId.length>200)throw new ApiError(422,'INVALID_EVENT','A valid event ID is required.');
  if(await db.billingEvent.findUnique({where:{provider_eventId:{provider:'razorpay',eventId}}}))return Response.json({received:true});
  const providerId=event.payload.subscription?.entity.id;const local=providerId?await db.subscription.findUnique({where:{providerId}}):null;
  if(local&&providerId){const {status,periodEnd}=await billingProvider.getSubscription(providerId);
   await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Organization" WHERE id=${local.organizationId} FOR UPDATE`;if(await tx.billingEvent.findUnique({where:{provider_eventId:{provider:'razorpay',eventId}}}))return;await tx.subscription.update({where:{id:local.id},data:{status,periodEnd}});await tx.billingEvent.create({data:{provider:'razorpay',eventId,eventType:event.event}});});
  }else{await db.billingEvent.upsert({where:{provider_eventId:{provider:'razorpay',eventId}},update:{},create:{provider:'razorpay',eventId,eventType:event.event}});}return Response.json({received:true});
 }
 if(resource==='runs'&&!id&&method==='POST'){
  const authHeader=req.headers.get('authorization');let organizationId:string;let allowedProject:string|undefined;let actor:string;
  if(authHeader?.startsWith('Bearer ')){const token=await db.projectToken.findUnique({where:{hash:hashToken(authHeader.slice(7))},include:{project:true}});if(!token||token.revokedAt||token.expiresAt<new Date()||token.project.archivedAt)throw new ApiError(401,'INVALID_TOKEN','The project token is invalid or expired.');organizationId=token.project.organizationId;allowedProject=token.projectId;actor=`token:${token.id}`;await rateLimit(actor,20);await db.projectToken.update({where:{id:token.id},data:{lastUsedAt:new Date()}});
  }else{sameOrigin(req);const workspace=await requireWorkspace(true);allowRole(workspace.role,['OWNER','ADMIN','DEVELOPER','QA']);organizationId=workspace.organizationId;actor=workspace.actor;await rateLimit(actor,20);}
  const input=sanitizeUpload(uploadInput.parse(await readJson(req)));if(allowedProject&&allowedProject!==input.projectId)throw new ApiError(403,'PROJECT_SCOPE','The token belongs to another project.');const project=await db.project.findFirst({where:{id:input.projectId,organizationId,archivedAt:null}});if(!project)throw new ApiError(404,'NOT_FOUND','Project not found.');
  const payloadHash=createHash('sha256').update(JSON.stringify(input)).digest('hex');const previous=await db.testRun.findUnique({where:{projectId_clientRunId:{projectId:project.id,clientRunId:input.clientRunId}}});if(previous){if(previous.payloadHash!==payloadHash)throw new ApiError(409,'IDEMPOTENCY_CONFLICT','This client run ID already has different content.');return Response.json({runId:previous.id,processingStatus:previous.processingStatus,dashboardUrl:`/dashboard/test-runs/${previous.id}`});}
  const plan=await planFor(organizationId);const runId=randomUUID();const objectKey=`${organizationId}/${project.id}/${runId}/report.json`;await storeReport(objectKey,input);let committed=false;
  try{const result=await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Organization" WHERE id=${organizationId} FOR UPDATE`;const duplicate=await tx.testRun.findUnique({where:{projectId_clientRunId:{projectId:project.id,clientRunId:input.clientRunId}}});if(duplicate){if(duplicate.payloadHash!==payloadHash)throw new ApiError(409,'IDEMPOTENCY_CONFLICT','This client run ID already has different content.');return duplicate;}
   const period=new Date().toISOString().slice(0,7);const usage=await tx.usage.upsert({where:{organizationId_period:{organizationId,period}},create:{organizationId,period,runCount:0},update:{}});if(usage.runCount>=plan.monthlyRunLimit)throw new ApiError(429,'RUN_LIMIT','The workspace monthly cloud run limit has been reached.');await tx.usage.update({where:{id:usage.id},data:{runCount:{increment:1}}});
   const report=input.report;const run=await tx.testRun.create({data:{id:runId,projectId:project.id,clientRunId:input.clientRunId,payloadHash,cliVersion:input.cliVersion,framework:report.framework,branch:input.branch??project.defaultBranch,commit:input.commit??'',environment:input.environment??project.environment,startedAt:new Date(report.startedAt),completedAt:new Date(report.finishedAt),durationMs:report.duration,overallScore:report.overallScore,categories:{},counts:{},coverage:report.routes,objectKey,outcome:'UNKNOWN',job:{create:{payload:input as unknown as Prisma.InputJsonValue}}}});await tx.auditLog.create({data:{organizationId,actor,action:'run.upload',targetId:run.id,requestId}});return run;});committed=result.id===runId;if(!committed)await removeReport(objectKey);return Response.json({runId:result.id,processingStatus:result.processingStatus,dashboardUrl:`/dashboard/test-runs/${result.id}`},{status:202});}catch(error){if(!committed)await removeReport(objectKey).catch(()=>{});throw error;}
 }
 const w=await requireWorkspace(true);await rateLimit(w.actor);if(method!=='GET')sameOrigin(req);
 if(resource==='me'&&method==='GET')return Response.json({organizationId:w.organizationId,role:w.role});
 if(resource==='projects'){
  if(!id&&method==='GET'){const take=Math.min(100,Math.max(1,Number(new URL(req.url).searchParams.get('limit')??25)||25));const cursor=new URL(req.url).searchParams.get('cursor');if(cursor&&!await db.project.findFirst({where:{id:cursor,organizationId:w.organizationId}}))throw new ApiError(422,'INVALID_CURSOR','Cursor is invalid.');const projects=await db.project.findMany({where:{organizationId:w.organizationId,archivedAt:null},take:take+1,orderBy:{id:'asc'},...(cursor?{cursor:{id:cursor},skip:1}:{})});return Response.json({projects:projects.slice(0,take),nextCursor:projects.length>take?projects[take-1].id:null});}
  if(!id&&method==='POST'){allowRole(w.role,['OWNER','ADMIN']);const values=projectInput.parse(await readJson(req,20000));const plan=await planFor(w.organizationId);const project=await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Organization" WHERE id=${w.organizationId} FOR UPDATE`;const count=await tx.project.count({where:{organizationId:w.organizationId,archivedAt:null}});if(count>=plan.projectLimit)throw new ApiError(429,'PROJECT_LIMIT','Your plan’s project limit has been reached.');const p=await tx.project.create({data:{...values,organizationId:w.organizationId}});await tx.auditLog.create({data:{organizationId:w.organizationId,actor:w.actor,action:'project.create',targetId:p.id,requestId}});return p});return Response.json({project},{status:201});}
  const project=await db.project.findFirst({where:{id,organizationId:w.organizationId,archivedAt:null}});if(!project)throw new ApiError(404,'NOT_FOUND','Project not found.');
  if(action==='tokens'){allowRole(w.role,['OWNER','ADMIN']);if(method==='GET')return Response.json({tokens:await db.projectToken.findMany({where:{projectId:project.id},select:{id:true,name:true,prefix:true,expiresAt:true,revokedAt:true},orderBy:{createdAt:'desc'},take:100})});if(method==='POST'){const {name}=z.object({name:z.string().min(1).max(100)}).strict().parse(await readJson(req,5000));const secret=newToken();const row=await db.$transaction(async tx=>{const token=await tx.projectToken.create({data:{projectId:project.id,name,hash:secret.hash,prefix:secret.prefix,expiresAt:new Date(Date.now()+90*86400000)}});await tx.auditLog.create({data:{organizationId:w.organizationId,actor:w.actor,action:'token.create',targetId:token.id,requestId}});return token;});return Response.json({id:row.id,token:secret.token,prefix:secret.prefix,expiresAt:row.expiresAt},{status:201});}if(method==='DELETE'&&child){await db.$transaction(async tx=>{const result=await tx.projectToken.updateMany({where:{id:child,projectId:project.id},data:{revokedAt:new Date()}});if(!result.count)throw new ApiError(404,'NOT_FOUND','Token not found.');await tx.auditLog.create({data:{organizationId:w.organizationId,actor:w.actor,action:'token.revoke',targetId:child,requestId}})});return Response.json({revoked:true});}}
  if(method==='GET')return Response.json({project});if(method==='PATCH'){allowRole(w.role,['OWNER','ADMIN']);const values=projectInput.partial().extend({qualityGate:gateInput.optional()}).strict().parse(await readJson(req,20000));return Response.json({project:await db.project.update({where:{id:project.id},data:values})});}if(method==='DELETE'){allowRole(w.role,['OWNER','ADMIN']);await db.$transaction([db.project.update({where:{id:project.id},data:{archivedAt:new Date()}}),db.projectToken.updateMany({where:{projectId:project.id},data:{revokedAt:new Date()}}),db.auditLog.create({data:{organizationId:w.organizationId,actor:w.actor,action:'project.archive',targetId:project.id,requestId}})]);return Response.json({archived:true});}
 }
 if(resource==='runs'){
  if(!id&&method==='GET'){const url=new URL(req.url);const cursor=url.searchParams.get('cursor');if(cursor&&!await db.testRun.findFirst({where:{id:cursor,project:{organizationId:w.organizationId}}}))throw new ApiError(422,'INVALID_CURSOR','Invalid cursor.');const take=Math.min(100,Math.max(1,Number(url.searchParams.get('limit')??25)||25));const rows=await db.testRun.findMany({where:{project:{organizationId:w.organizationId,archivedAt:null},deletedAt:null,...(url.searchParams.get('projectId')?{projectId:url.searchParams.get('projectId')!}:{}),...(url.searchParams.get('branch')?{branch:url.searchParams.get('branch')!}:{})},select:{id:true,projectId:true,overallScore:true,outcome:true,processingStatus:true,completedAt:true,branch:true,environment:true},orderBy:{id:'asc'},take:take+1,...(cursor?{cursor:{id:cursor},skip:1}:{})});return Response.json({runs:rows.slice(0,take),nextCursor:rows.length>take?rows[take-1].id:null});}
  const run=await db.testRun.findFirst({where:{id,deletedAt:null,project:{organizationId:w.organizationId,archivedAt:null}},include:{results:true,observations:{include:{issue:true}}}});if(!run)throw new ApiError(404,'NOT_FOUND','Run not found.');if(action==='download'&&method==='GET')return Response.json({url:await downloadReport(run.objectKey)});if(method==='GET'){const {objectKey:unused,...safe}=run;void unused;return Response.json({run:safe});}if(method==='DELETE'){allowRole(w.role,['OWNER','ADMIN']);await removeReport(run.objectKey);await db.testRun.update({where:{id:run.id},data:{deletedAt:new Date()}});return Response.json({deleted:true});}
 }
 if(resource==='issues'){if(method==='GET'&&!id){const url=new URL(req.url);const cursor=url.searchParams.get('cursor');if(cursor&&!await db.issue.findFirst({where:{id:cursor,project:{organizationId:w.organizationId}}}))throw new ApiError(422,'INVALID_CURSOR','Invalid cursor.');const rows=await db.issue.findMany({where:{project:{organizationId:w.organizationId,archivedAt:null},...(url.searchParams.get('projectId')?{projectId:url.searchParams.get('projectId')!}:{})},take:26,orderBy:{id:'asc'},...(cursor?{cursor:{id:cursor},skip:1}:{})});return Response.json({issues:rows.slice(0,25),nextCursor:rows.length>25?rows[24].id:null});}if(method==='PATCH'&&id){allowRole(w.role,['OWNER','ADMIN','DEVELOPER','QA']);const values=z.object({status:z.enum(['OPEN','RESOLVED','IGNORED','ACCEPTED'])}).strict().parse(await readJson(req,5000));const issue=await db.issue.findFirst({where:{id,project:{organizationId:w.organizationId}}});if(!issue)throw new ApiError(404,'NOT_FOUND','Issue not found.');await db.$transaction([db.issue.update({where:{id},data:values}),db.auditLog.create({data:{organizationId:w.organizationId,actor:w.actor,action:`issue.${values.status.toLowerCase()}`,targetId:id,requestId}})]);return Response.json({updated:true});}}
 if(resource==='billing'){
  if(id==='plans'&&method==='GET')return Response.json({plans:await db.plan.findMany({select:{key:true,name:true,amountMinor:true,currency:true,projectLimit:true,monthlyRunLimit:true}})});
  if(id==='subscription'&&method==='GET')return Response.json({subscription:await db.subscription.findUnique({where:{organizationId:w.organizationId},include:{plan:true}})});
  if(id==='checkout'&&method==='POST'){allowRole(w.role,['OWNER']);const plan=await db.plan.findUnique({where:{key:'pro'}});if(!plan?.providerPlanId)throw new ApiError(503,'BILLING_NOT_CONFIGURED','The Pro provider plan is not configured.');const existing=await db.subscription.findUnique({where:{organizationId:w.organizationId}});if(existing&&!['cancelled','completed','expired'].includes(existing.status))throw new ApiError(409,'SUBSCRIPTION_EXISTS','A subscription already exists. Manage it before creating another.');const {id:providerId,checkoutUrl}=await billingProvider.createSubscription(plan.providerPlanId,w.organizationId);await db.subscription.upsert({where:{organizationId:w.organizationId},create:{organizationId:w.organizationId,planId:plan.id,providerId,status:'created'},update:{planId:plan.id,providerId,status:'created',periodEnd:null}});return Response.json({checkoutUrl});}
  if(id==='cancel'&&method==='POST'){allowRole(w.role,['OWNER']);const sub=await db.subscription.findUnique({where:{organizationId:w.organizationId}});if(!sub)throw new ApiError(404,'NOT_FOUND','Subscription not found.');await billingProvider.cancelSubscription(sub.providerId);return Response.json({cancellationRequested:true});}
 }
 if(resource==='usage'&&method==='GET')return Response.json({plan:await planFor(w.organizationId),usage:await db.usage.findUnique({where:{organizationId_period:{organizationId:w.organizationId,period:new Date().toISOString().slice(0,7)}}})});
 throw new ApiError(404,'NOT_FOUND','Endpoint not found.');
});
async function boundedText(req:Request,max:number){const reader=req.body?.getReader();if(!reader)throw new ApiError(422,'EMPTY_BODY','Body required.');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new ApiError(413,'PAYLOAD_TOO_LARGE','Webhook is too large.')}chunks.push(value)}return Buffer.concat(chunks).toString('utf8')}
export {handler as GET,handler as POST,handler as PATCH,handler as DELETE};
