import type { SuggestionMap } from "./types.js";

export const eslintSuggestions: SuggestionMap = {
  "react/jsx-key": {
    code: "react/jsx-key",
    title: "React Missing List Key",
    problem: "Iterating over an array to render JSX elements without a unique key prop.",
    whyItMatters: "React uses key props to track list item identity during reconciliation, preventing UI glitches.",
    suggestedFix: ["Add a stable unique key prop to elements rendered from an iterator. Prefer a persistent item ID instead of the array index."],
    shortFix: "Add a stable unique key prop to elements rendered from an iterator. Prefer a persistent item ID instead of the array index.",
  },
  "eslint:react/jsx-key": {
    code: "eslint:react/jsx-key",
    title: "React Missing List Key",
    problem: "Iterating over an array to render JSX elements without a unique key prop.",
    whyItMatters: "React uses key props to track list item identity during reconciliation.",
    suggestedFix: ["Add a stable unique key prop to elements rendered from an iterator. Prefer a persistent item ID instead of the array index."],
    shortFix: "Add a stable unique key prop to elements rendered from an iterator. Prefer a persistent item ID instead of the array index.",
  },
  "jsx-a11y/alt-text": {
    code: "jsx-a11y/alt-text",
    title: "Missing Image Alt Text",
    problem: "Image elements (<img>) lack an alt prop.",
    whyItMatters: "Screen readers and assistive technologies require descriptive alt text.",
    suggestedFix: ["Add a meaningful alt attribute to informative images or alt=\"\" for decorative images."],
    shortFix: "Add a meaningful alt attribute to informative images or alt=\"\" for decorative images.",
  },
  "eslint:jsx-a11y/alt-text": {
    code: "eslint:jsx-a11y/alt-text",
    title: "Missing Image Alt Text",
    problem: "Image elements (<img>) lack an alt prop.",
    whyItMatters: "Screen readers and assistive technologies require descriptive alt text.",
    suggestedFix: ["Add a meaningful alt attribute to informative images or alt=\"\" for decorative images."],
    shortFix: "Add a meaningful alt attribute to informative images or alt=\"\" for decorative images.",
  },
  "@next/next/no-img-element": {
    code: "@next/next/no-img-element",
    title: "Next.js Image Optimization",
    problem: "Using native <img> tags instead of the Next.js <Image /> component.",
    whyItMatters: "Native <img> tags bypass Next.js automatic image optimization and lazy loading.",
    suggestedFix: ["Replace the raw <img> element with Next.js <Image> from next/image when appropriate and provide width/height or fill configuration."],
    shortFix: "Replace the raw <img> element with Next.js <Image> from next/image when appropriate and provide width/height or fill configuration.",
  },
  "eslint:@next/next/no-img-element": {
    code: "eslint:@next/next/no-img-element",
    title: "Next.js Image Optimization",
    problem: "Using native <img> tags instead of the Next.js <Image /> component.",
    whyItMatters: "Native <img> tags bypass Next.js automatic image optimization.",
    suggestedFix: ["Replace the raw <img> element with Next.js <Image> from next/image when appropriate and provide width/height or fill configuration."],
    shortFix: "Replace the raw <img> element with Next.js <Image> from next/image when appropriate and provide width/height or fill configuration.",
  },
  "react-hooks/purity": {
    code: "react-hooks/purity",
    title: "React Hooks Purity",
    problem: "Calling an impure function (such as Date.now() or Math.random()) inside a component render body.",
    whyItMatters: "React components must be pure functions of props and state. Impure render logic causes non-deterministic renders.",
    suggestedFix: ["Do not call impure functions such as Date.now() directly during render. Compute the value in an appropriate state/effect/event boundary or otherwise make rendering deterministic."],
    shortFix: "Do not call impure functions such as Date.now() directly during render. Compute the value in an appropriate state/effect/event boundary or otherwise make rendering deterministic.",
  },
  "eslint:react-hooks/purity": {
    code: "eslint:react-hooks/purity",
    title: "React Hooks Purity",
    problem: "Calling an impure function inside a component render body.",
    whyItMatters: "React components must be pure functions of props and state.",
    suggestedFix: ["Do not call impure functions such as Date.now() directly during render. Compute the value in an appropriate state/effect/event boundary or otherwise make rendering deterministic."],
    shortFix: "Do not call impure functions such as Date.now() directly during render. Compute the value in an appropriate state/effect/event boundary or otherwise make rendering deterministic.",
  },
  "react-hooks/exhaustive-deps": {
    code: "react-hooks/exhaustive-deps",
    title: "React Hooks Exhaustive Dependencies",
    problem: "Effect or memo callback has missing or incorrect dependencies.",
    whyItMatters: "Missing dependencies cause stale closures and out-of-sync component state.",
    suggestedFix: ["Include all referenced variables in the useEffect/useCallback/useMemo dependency array."],
    shortFix: "Include all referenced variables in the hook dependency array or refactor function scope.",
  },
  "eslint:react-hooks/exhaustive-deps": {
    code: "eslint:react-hooks/exhaustive-deps",
    title: "React Hooks Exhaustive Dependencies",
    problem: "Effect or memo callback has missing or incorrect dependencies.",
    whyItMatters: "Missing dependencies cause stale closures and out-of-sync component state.",
    suggestedFix: ["Include all referenced variables in the useEffect/useCallback/useMemo dependency array."],
    shortFix: "Include all referenced variables in the hook dependency array or refactor function scope.",
  },
  "@typescript-eslint/no-unused-vars": {
    code: "@typescript-eslint/no-unused-vars",
    title: "Unused Variables",
    problem: "Variables or parameters declared but never read.",
    whyItMatters: "Unused variables clutter codebases and often signal leftover code or missing logic.",
    suggestedFix: ["Remove unused variables or prefix unused parameters with an underscore."],
    shortFix: "Remove unused variables or prefix unused parameters with an underscore.",
  },
  "eslint:@typescript-eslint/no-unused-vars": {
    code: "eslint:@typescript-eslint/no-unused-vars",
    title: "Unused Variables",
    problem: "Variables or parameters declared but never read.",
    whyItMatters: "Unused variables clutter codebases and often signal leftover code or missing logic.",
    suggestedFix: ["Remove unused variables or prefix unused parameters with an underscore."],
    shortFix: "Remove unused variables or prefix unused parameters with an underscore.",
  },
};
