import type { SuggestionMap } from "./types.js";

export const responsiveSuggestions: SuggestionMap = {
  "viewport-overflow": {
    code: "viewport-overflow",
    title: "Viewport Overflow",
    problem: "An element extends outside the visible viewport.",
    whyItMatters: "Horizontal overflow creates a broken mobile experience.",
    suggestedFix: ["Use max-width: 100%;", "Use overflow-x: hidden carefully.", "Check fixed width elements."],
    shortFix: "Constrain fixed-width elements and media.",
  },
  "horizontal-scroll": {
    code: "horizontal-scroll",
    title: "Horizontal Scroll",
    problem: "The page width exceeds the viewport width.",
    whyItMatters: "Users may need to pan sideways to read content on mobile.",
    suggestedFix: ["Audit large containers.", "Replace fixed widths with responsive widths.", "Use max-width: 100%;"],
    shortFix: "Remove layout overflow.",
  },
  "missing-viewport": {
    code: "missing-viewport",
    title: "Missing Viewport Meta",
    problem: "The document is missing a viewport meta tag.",
    whyItMatters: "Mobile browsers may render the page at desktop width.",
    suggestedFix: ['<meta name="viewport" content="width=device-width, initial-scale=1" />'],
    shortFix: "Add the viewport meta tag.",
  },
  "text-clipping": {
    code: "text-clipping",
    title: "Text Clipping",
    problem: "Text content appears clipped.",
    whyItMatters: "Users may miss important content or controls.",
    suggestedFix: ["Allow wrapping.", "Avoid fixed heights for dynamic content.", "Test long labels."],
    shortFix: "Allow text to wrap and grow.",
  },
  "image-overflow": {
    code: "image-overflow",
    title: "Image Overflow",
    problem: "An image is wider than the viewport.",
    whyItMatters: "Oversized images can break the page layout on small screens.",
    suggestedFix: ["img { max-width: 100%; height: auto; }"],
    shortFix: "Constrain images with max-width.",
  },
  "responsive-image": {
    code: "responsive-image",
    title: "Non-responsive Image",
    problem: "A large image does not provide responsive sources.",
    whyItMatters: "Mobile users may download unnecessarily large images.",
    suggestedFix: ["Use srcset and sizes for responsive images."],
    shortFix: "Add srcset/sizes.",
  },
  "cut-off-control": {
    code: "cut-off-control",
    title: "Cut-off Control",
    problem: "An interactive control is clipped horizontally.",
    whyItMatters: "Users may not be able to activate or read the control.",
    suggestedFix: ["Avoid fixed positioning/widths for controls.", "Test controls at narrow widths."],
    shortFix: "Make controls fit their container.",
  },
  "fixed-header-overlap": {
    code: "fixed-header-overlap",
    title: "Fixed Header Overlap",
    problem: "A fixed or sticky header overlaps page content.",
    whyItMatters: "Content can become unreadable or inaccessible.",
    suggestedFix: ["Add top padding/scroll-margin-top equal to the header height."],
    shortFix: "Offset content for the fixed header.",
  },
  "layout-shift": {
    code: "layout-shift",
    title: "Layout Shift",
    problem: "Content shifts after the page starts loading.",
    whyItMatters: "Unexpected movement hurts usability and Core Web Vitals.",
    suggestedFix: ["Reserve image/media dimensions.", "Avoid injecting content above existing content."],
    shortFix: "Reserve layout space before content loads.",
  },
};
