import type { SuggestionMap } from "./types.js";

export const seoSuggestions: SuggestionMap = {
  "missing-title": {
    code: "missing-title",
    title: "Missing Title",
    problem: "This page does not contain a document title.",
    whyItMatters: "Search engines and browser tabs rely on concise page titles to identify content.",
    suggestedFix: ["<title>Your Page Title</title>"],
    shortFix: "Add a descriptive <title> tag.",
  },
  "missing-description": {
    code: "missing-description",
    title: "Missing Meta Description",
    problem: "This page does not contain a meta description.",
    whyItMatters: "Search engines often use descriptions for result snippets and users need useful context.",
    suggestedFix: ['<meta name="description" content="Clear page description." />'],
    shortFix: "Add a clear meta description.",
  },
  "missing-canonical": {
    code: "missing-canonical",
    title: "Missing Canonical",
    problem: "This page does not contain a canonical URL.",
    whyItMatters: "Search engines may index duplicate versions of the same page.",
    suggestedFix: ['<link rel="canonical" href="https://example.com/page" />'],
    shortFix: "Add a canonical link tag.",
  },
  "missing-open-graph": {
    code: "missing-open-graph",
    title: "Missing Open Graph",
    problem: "Social platforms cannot generate a rich preview.",
    whyItMatters: "Shared links may look incomplete and reduce click-through from social platforms.",
    suggestedFix: [
      '<meta property="og:title" content="Your Page Title" />',
      '<meta property="og:description" content="Page Description" />',
      '<meta property="og:image" content="/og-image.png" />',
    ],
    shortFix: "Add Open Graph title, description, and image tags.",
  },
  "missing-twitter-card": {
    code: "missing-twitter-card",
    title: "Missing Twitter Card",
    problem: "Twitter/X cannot display a rich preview.",
    whyItMatters: "Shared pages may appear as plain links instead of rich social cards.",
    suggestedFix: ['<meta name="twitter:card" content="summary_large_image" />'],
    shortFix: "Add Twitter card metadata.",
  },
  "missing-h1": {
    code: "missing-h1",
    title: "Missing H1",
    problem: "This page does not contain a primary H1 heading.",
    whyItMatters: "Users, assistive technology, and search engines need a clear top-level heading.",
    suggestedFix: ["<h1>Clear Page Heading</h1>"],
    shortFix: "Add one descriptive H1.",
  },
  "multiple-h1": {
    code: "multiple-h1",
    title: "Multiple H1 Tags",
    problem: "This page contains more than one H1 heading.",
    whyItMatters: "Multiple primary headings can weaken page structure and accessibility.",
    suggestedFix: ["Use one <h1>, then use <h2> and <h3> for subsections."],
    shortFix: "Keep one H1 and demote secondary headings.",
  },
  "missing-alt": {
    code: "missing-alt",
    title: "Missing Image Alt Text",
    problem: "One or more images do not provide alternative text.",
    whyItMatters: "Screen readers need alt text to explain meaningful images.",
    suggestedFix: ['<img src="..." alt="Meaningful description" />'],
    shortFix: "Add meaningful alt text to images.",
  },
  "missing-structured-data": {
    code: "missing-structured-data",
    title: "Missing Structured Data",
    problem: "This page does not expose structured data.",
    whyItMatters: "Structured data helps search engines understand page entities and may enable rich results.",
    suggestedFix: ['<script type="application/ld+json">{ "...": "..." }</script>'],
    shortFix: "Add relevant JSON-LD structured data.",
  },
  "duplicate-title": {
    code: "duplicate-title",
    title: "Duplicate Title",
    problem: "Multiple pages share the same document title.",
    whyItMatters: "Duplicate titles make pages harder to distinguish in search results.",
    suggestedFix: ["Give every important route a unique, descriptive title."],
    shortFix: "Make page titles unique.",
  },
  "duplicate-description": {
    code: "duplicate-description",
    title: "Duplicate Description",
    problem: "Multiple pages share the same meta description.",
    whyItMatters: "Duplicate descriptions reduce clarity in search snippets.",
    suggestedFix: ["Write a unique meta description for each important route."],
    shortFix: "Make meta descriptions unique.",
  },
  "missing-seo-file": {
    code: "missing-seo-file",
    title: "Missing SEO File",
    problem: "An expected SEO file such as robots.txt or sitemap.xml is unavailable.",
    whyItMatters: "Search engines use these files to discover and crawl site content.",
    suggestedFix: ["Publish /robots.txt and /sitemap.xml from the production host."],
    shortFix: "Add or fix robots.txt and sitemap.xml.",
  },
  "broken-canonical": {
    code: "broken-canonical",
    title: "Broken Canonical",
    problem: "The canonical URL is unavailable or returns an error.",
    whyItMatters: "Search engines may ignore broken canonical hints.",
    suggestedFix: ["Point canonical links to a valid, reachable production URL."],
    shortFix: "Fix the canonical URL.",
  },
};
