import {createHash} from 'node:crypto';
import {db} from '../src/server/db';
import type {SanitizedUpload} from '../src/server/validation';
export async function processOne(){const now=new Date();const candidate=await db.importJob.findFirst({where:{OR:[{status:'QUEUED',availableAt:{lte:now}},{status:'PROCESSING',leaseUntil:{lt:now}}]},orderBy:{createdAt:'asc'}});if(!candidate)return false;const claimed=await db.importJob.updateMany({where:{id:candidate.id,OR:[{status:'QUEUED'},{status:'PROCESSING',leaseUntil:{lt:now}}]},data:{status:'PROCESSING',leaseUntil:new Date(Date.now()+60000),attempts:{increment:1}}});if(!claimed.count)return true;
 try{await db.$transaction(async tx=>{const run=await tx.testRun.findUniqueOrThrow({where:{id:candidate.runId},include:{project:true}});await tx.$queryRaw`SELECT id FROM "Project" WHERE id=${run.projectId} FOR UPDATE`;if(run.processingStatus==='COMPLETE'){await tx.importJob.update({where:{id:candidate.id},data:{status:'COMPLETE',payload:{},leaseUntil:null}});return;}const payload=candidate.payload as unknown as SanitizedUpload;const results=payload.report.results.map(r=>({...r,issues:r.issues.map(i=>({...i,fingerprint:createHash('sha256').update(JSON.stringify([run.branch,run.environment,i.fingerprint])).digest('hex')}))}));const prev=await tx.testRun.findFirst({where:{projectId:run.projectId,environment:run.environment,branch:run.branch,completedAt:{lt:run.completedAt},processingStatus:'COMPLETE',deletedAt:null},orderBy:{completedAt:'desc'},include:{observations:{include:{issue:true}},results:true}});
  const categories:Record<string,number>={};for(const r of results){if(r.score!==undefined&&r.status!=='SKIPPED')categories[r.name]=r.score;}
  const counts={passed:results.filter(r=>r.status==='PASS').length,warnings:results.filter(r=>r.status==='WARNING').length,errors:results.filter(r=>r.status==='FAIL'||r.status==='ERROR').length,skipped:results.filter(r=>r.status==='SKIPPED').length};const outcome=counts.errors?'FAIL':counts.warnings?'WARNING':'PASS';
  await tx.testResult.createMany({data:results.map(r=>({runId:run.id,name:r.name,category:r.category??r.name,outcome:r.status,score:r.score??null,durationMs:r.duration,message:r.message??''}))});
  const fingerprints=new Set<string>();for(const r of results){for(const i of r.issues){if(fingerprints.has(i.fingerprint))continue;fingerprints.add(i.fingerprint);const existing=await tx.issue.findUnique({where:{projectId_fingerprint:{projectId:run.projectId,fingerprint:i.fingerprint}}});const inPrevious=prev?.observations.some(o=>o.issue.fingerprint===i.fingerprint);const change=!existing?'New':inPrevious?'Existing':existing.status==='RESOLVED'?'Regressed':'Existing';const issue=await tx.issue.upsert({where:{projectId_fingerprint:{projectId:run.projectId,fingerprint:i.fingerprint}},create:{projectId:run.projectId,fingerprint:i.fingerprint,title:i.title,category:r.name,severity:i.severity,route:i.url,selector:i.selector,actual:i.message,suggestion:i.suggestion.shortFix,firstSeenAt:run.completedAt,lastSeenAt:run.completedAt},update:existing&&existing.lastSeenAt>run.completedAt?{}:{lastSeenAt:run.completedAt,title:i.title,actual:i.message,...(existing?.status==='RESOLVED'?{status:'OPEN' as const}:{})}});await tx.issueOccurrence.create({data:{runId:run.id,issueId:issue.id,change}});}}
  // Only resolve when route coverage and category execution are demonstrably comparable.
  const currentRoutes=new Set(payload.report.routes);const previousRoutes=Array.isArray(prev?.coverage)?prev.coverage.filter((v):v is string=>typeof v==='string'):[];const coverageComparable=previousRoutes.length>0&&previousRoutes.every(r=>currentRoutes.has(r));const hasNewer=await tx.testRun.count({where:{projectId:run.projectId,environment:run.environment,branch:run.branch,completedAt:{gt:run.completedAt},processingStatus:'COMPLETE'}});
  if(prev&&coverageComparable&&!hasNewer){for(const o of prev.observations){if(o.change==='Fixed'||fingerprints.has(o.issue.fingerprint))continue;const check=results.find(r=>r.name===o.issue.category&&r.status!=='SKIPPED'&&r.status!=='ERROR');if(!check)continue;const previouslySuccessful=prev.results.some(r=>r.name===check.name&&r.outcome!=='SKIPPED'&&r.outcome!=='ERROR');if(!previouslySuccessful)continue;if(o.issue.status==='OPEN'){await tx.issue.update({where:{id:o.issueId},data:{status:'RESOLVED'}});await tx.issueOccurrence.create({data:{runId:run.id,issueId:o.issueId,change:'Fixed'}});}}}
  await tx.testRun.update({where:{id:run.id},data:{categories,counts,outcome,processingStatus:'COMPLETE',scoreDelta:prev?run.overallScore-prev.overallScore:null}});await tx.importJob.update({where:{id:candidate.id},data:{status:'COMPLETE',payload:{},leaseUntil:null}});
 },{timeout:30000});}catch{const attempts=candidate.attempts+1;await db.importJob.update({where:{id:candidate.id},data:{status:attempts>=5?'FAILED':'QUEUED',error:'Import could not be completed.',leaseUntil:null,availableAt:new Date(Date.now()+Math.min(60000,2000*2**attempts))}});if(attempts>=5)await db.testRun.update({where:{id:candidate.runId},data:{processingStatus:'FAILED'}});}return true;
}
