import type { CloudData } from './models';
const categories = {Build:100,TypeScript:100,ESLint:100,SEO:98,Accessibility:96,Performance:87,Lighthouse:90,Responsive:94,Console:100,Network:95,Links:98,Images:96,API:89,E2E:94,Visual:91};
export const demoData:CloudData = {
projects:[
{id:'phoenix',name:'Phoenix Website',description:'Our customer-facing platform and marketing website.',url:'https://phoenix.example',repository:'https://github.com/example/phoenix',framework:'Next.js',environment:'Production',branch:'main',score:94,previous:87,errors:2,warnings:7,lastRun:'10 minutes ago',color:'#7565e7'},
{id:'sportomic',name:'Sportomic',description:'Sports bookings, made simple.',url:'https://sportomic.example',repository:'',framework:'React',environment:'Staging',branch:'dev',score:88,previous:84,errors:1,warnings:4,lastRun:'42 minutes ago',color:'#e49b4a'},
{id:'website',name:'Agency Website',description:'A new home for our creative studio.',url:'https://studio.example',repository:'',framework:'Vue',environment:'Production',branch:'main',score:72,previous:78,errors:6,warnings:9,lastRun:'Yesterday',color:'#e07b94'},
{id:'orbit',name:'Orbit Dashboard',description:'The internal workspace for our team.',url:'https://orbit.example',repository:'',framework:'Vite',environment:'Development',branch:'main',score:98,previous:96,errors:0,warnings:2,lastRun:'Yesterday',color:'#4bb39a'}],
runs:Array.from({length:18},(_,i)=>{const p=i%4; const names=['Phoenix Website','Sportomic','Agency Website','Orbit Dashboard']; const ids=['phoenix','sportomic','website','orbit']; const score=i<4?[94,88,72,98][p]:Math.min(99,78+(i*7)%20); return {id:`run-${128-i}`,number:128-i,projectId:ids[p],project:names[p],branch:p===1?'dev':'main',commit:['8f73d2a','b9c42e1','a12d8f3','c08e9ab'][p],environment:p===1?'Staging':'Production',score,previous:score-7,status:score>=90?'Passed':score>=80?'Warning':'Failed',duration:['1m 32s','2m 04s','1m 51s','58s'][p],date:i<2?'Oct 02, 2026':`Sep ${30-Math.floor(i/3)}, 2026`,passed:43-i%7,warnings:p+2,errors:p===2?6:p===0?2:0,categories:{...categories,Performance:score-7}};}),
issues:[
{id:'contrast',title:'Button has insufficient color contrast',projectId:'phoenix',project:'Phoenix Website',category:'Accessibility',severity:'Warning',route:'/login',selector:'.login-button',status:'Open',change:'New',expected:'Contrast ratio ≥ 4.5:1',actual:'Contrast ratio 3.2:1',fix:'Increase contrast between the button background and label. Use a darker background or a lighter text color.',firstSeen:'Oct 02, 2026',lastSeen:'Oct 02, 2026'},
{id:'image',title:'Hero image exceeds recommended size',projectId:'phoenix',project:'Phoenix Website',category:'Performance',severity:'Warning',route:'/',selector:'.hero-image',status:'Open',change:'Existing',expected:'Image size below 250 KB',actual:'Image size 1.4 MB',fix:'Convert the image to WebP or AVIF and serve responsive sizes using srcset.',firstSeen:'Sep 29, 2026',lastSeen:'Oct 02, 2026'},
{id:'api',title:'Users endpoint returned an error',projectId:'sportomic',project:'Sportomic',category:'API',severity:'Error',route:'/api/users',selector:'GET /api/users',status:'Open',change:'Regressed',expected:'HTTP 200',actual:'HTTP 500',fix:'Inspect the endpoint server logs and verify its database connection.',firstSeen:'Sep 28, 2026',lastSeen:'Oct 02, 2026'},
{id:'meta',title:'Page is missing a meta description',projectId:'website',project:'Agency Website',category:'SEO',severity:'Error',route:'/about',selector:'meta[name="description"]',status:'Open',change:'New',expected:'A unique descriptive meta description',actual:'No description found',fix:'Add a concise description that summarizes this page.',firstSeen:'Oct 01, 2026',lastSeen:'Oct 01, 2026'},
{id:'link',title:'Footer link points to a missing page',projectId:'website',project:'Agency Website',category:'Links',severity:'Error',route:'/contact',selector:'footer a',status:'Open',change:'Existing',expected:'A successful response',actual:'HTTP 404',fix:'Update the footer link or restore the missing page.',firstSeen:'Sep 30, 2026',lastSeen:'Oct 01, 2026'},
{id:'alt',title:'Product image is missing alternative text',projectId:'phoenix',project:'Phoenix Website',category:'Accessibility',severity:'Warning',route:'/products',selector:'img.product',status:'Resolved',change:'Fixed',expected:'Meaningful alternative text',actual:'Alternative text now present',fix:'Keep the descriptive alt attribute in the product component.',firstSeen:'Sep 29, 2026',lastSeen:'Oct 02, 2026'}]
};
